### ISSUE TITLE
Solution Day 13 

### ISSUE THREAD

**Issue by simonschnake** [iskyd/advent-of-code-julia#1]
Not a real issue, 
just wanted to mention that you could use
`eval(Meta.parse(...))` do get the input lines to lists.

Thanks for the nice solution :)

**Comment by iskyd** [comment]
Thanks for pointing out Meta.parse
I'm usually not a fan of eval so I try to avoid it even if it fits well in problems like advent of code.
Another way to parse the input for part 2 could be
`v = [JSON.parse(line) for line in readlines("input.txt") if line !== ""]`

I did the get_pairs parsing for part 1 using ResumableFunctions because there's no need to load the whole input in memory.

I'm updating the code using the above snippet to make it more readable. Using get_paris() for part 2 gives us no advantage since we always load the whole input in memory.

**Comment by simonschnake** [comment]
Sure, it is the security nightmare :D. 
Also a nice way to read in the data
